version: '3.8'
services:
  backend:
    image: backend
    build:
      context: ./server  # Point to the server directory where your Dockerfile is located
      dockerfile: Dockerfile 
    ports:
      - "4000:3000"  # Map the port for the Node.js server
    volumes:
      - ./server:/app  # Mount the current directory to the container (optional for development)

  frontend:
    image: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5000:5173"