name: Formatter & CI
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        project: [server, client]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install Dependencies
        run: |
          cd ${{ matrix.project }}
          npm ci
          if [ "${{ matrix.project }}" == "server" ]; then
            python -m pip install --upgrade pip
            pip install -r req.txt
          fi

      - name: TEST AND BULID
        env:
          TESTING_ENV: ${{ secrets.TESTING_ENV }}
        run: |
          cd ${{ matrix.project }}
          if [ "${{ matrix.project }}" == "server" ]; then
            npm test
            timeout --preserve-status 5s node index.js || true
          elif [ "${{ matrix.project }}" == "client" ]; then
            npm run build
          fi